// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNrO4POnghl4oBALDbNAKAHF9isqmCVw',
    appId: '1:564643852041:web:7638cc3a902dbc2100edd8',
    messagingSenderId: '564643852041',
    projectId: 'chat-app-379f8',
    authDomain: 'chat-app-379f8.firebaseapp.com',
    storageBucket: 'chat-app-379f8.firebasestorage.app',
    measurementId: 'G-YQLG6FP7WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWmeW9_J1B_SSkVZE3Wd7NMCCs_Uc66iU',
    appId: '1:564643852041:android:52d585576872c12800edd8',
    messagingSenderId: '564643852041',
    projectId: 'chat-app-379f8',
    storageBucket: 'chat-app-379f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfaueP_-8ifRd9mJqURoqiAAOrjpx4XRo',
    appId: '1:564643852041:ios:02062297f92a702b00edd8',
    messagingSenderId: '564643852041',
    projectId: 'chat-app-379f8',
    storageBucket: 'chat-app-379f8.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfaueP_-8ifRd9mJqURoqiAAOrjpx4XRo',
    appId: '1:564643852041:ios:02062297f92a702b00edd8',
    messagingSenderId: '564643852041',
    projectId: 'chat-app-379f8',
    storageBucket: 'chat-app-379f8.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
